// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwQHZmipJUlkoFwIJ3NHoKIjqjoRo_AXQ',
    appId: '1:283287629968:web:1d4f9a05b7183faa0c6815',
    messagingSenderId: '283287629968',
    projectId: 'parcial4bd-d9af1',
    authDomain: 'parcial4bd-d9af1.firebaseapp.com',
    storageBucket: 'parcial4bd-d9af1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4CK62jhknv00mftbKsOscGF5gttdYGiY',
    appId: '1:283287629968:android:697ec6e5a230198b0c6815',
    messagingSenderId: '283287629968',
    projectId: 'parcial4bd-d9af1',
    storageBucket: 'parcial4bd-d9af1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaH2-9DbfaRdgX5JErfTg64eO7WxDlvu0',
    appId: '1:283287629968:ios:6d0d729944af49530c6815',
    messagingSenderId: '283287629968',
    projectId: 'parcial4bd-d9af1',
    storageBucket: 'parcial4bd-d9af1.appspot.com',
    iosClientId: '283287629968-l7v2tvffk5bc2bu3dfhhe8p93kvlbkkk.apps.googleusercontent.com',
    iosBundleId: 'com.example.parcial4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaH2-9DbfaRdgX5JErfTg64eO7WxDlvu0',
    appId: '1:283287629968:ios:6d0d729944af49530c6815',
    messagingSenderId: '283287629968',
    projectId: 'parcial4bd-d9af1',
    storageBucket: 'parcial4bd-d9af1.appspot.com',
    iosClientId: '283287629968-l7v2tvffk5bc2bu3dfhhe8p93kvlbkkk.apps.googleusercontent.com',
    iosBundleId: 'com.example.parcial4',
  );
}
